zds/member/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views


urlpatterns = patterns('',
    url(r'^voir/(?P<user_name>.+)$', views.details),
    url(r'^profil/editer$', views.edit_profile),
    url(r'^profil/modifier/(?P<user_pk>\d+)', views.modify_profile),

    url(r'^publications$', views.publications),
    url(r'^actions$', views.actions),

    url(r'^parametres/profil$', views.settings_profile),
    url(r'^parametres/compte$', views.settings_account),

    url(r'^connexion$', views.login_view),
    url(r'^inscription$', views.register_view),
    url(r'^deconnexion/$', views.logout_view),
    url(r'^$', views.index),
)

zds/urls.py
# encoding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User, Group

import pages.views
import settings


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^tutoriels/', include('zds.tutorial.urls')),
    url(r'^forums/', include('zds.forum.urls')),
    url(r'^mp/', include('zds.mp.urls')),
    url(r'^membres/', include('zds.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('zds.pages.urls')),
    url(r'^galerie/', include('zds.gallery.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pages.views.home),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SERVE:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

zds/member/models.py
# coding: utf-8

from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q
from hashlib import md5

from zds.forum.models import Post, Topic
from zds.utils.models import Alert
from zds.tutorial.models import Tutorial


class Profile(models.Model):

    '''Represents an user profile'''
    class Meta:
        verbose_name = 'Profil'
        verbose_name_plural = 'Profils'
        permissions = (
                ("moderation",u"Moderer un membre"),
                ("show_ip",u"Afficher les IP d'un membre"),
        )

    user = models.ForeignKey(User, unique=True, verbose_name='Utilisateur')
    
    last_ip_address = models.CharField('Adresse IP', max_length=15, blank=True)

    site = models.CharField('Site internet', max_length=128, blank=True)
    show_email = models.BooleanField('Afficher adresse mail publiquement',
                                     default=True)

    avatar_url = models.CharField(
        'URL de l\'avatar', max_length=128, null=True, blank=True
    )

    biography = models.TextField('Biographie', blank=True)
    
    karma = models.IntegerField('Karma', default=0)
    
    sign = models.TextField('Signature', blank=True)
    
    show_sign = models.BooleanField('Voir les signatures',
                                     default=True)
    
    hover_or_click = models.BooleanField('Survol ou click ?',
                                     default=True)
    
    can_read = models.BooleanField('Possibilité de lire', default=True)
    end_ban_read = models.DateTimeField('Fin d\'interdiction de lecture', null=True, blank=True)
    
    can_write = models.BooleanField('Possibilité d\'écrire', default=True)
    end_ban_write = models.DateTimeField('Fin d\'interdiction d\'ecrire', null=True, blank=True)

    def __unicode__(self):
        '''Textual forum of a profile'''
        return self.user.username

    def get_absolute_url(self):
        '''Absolute URL to the profile page'''
        return '/membres/voir/{0}'.format(self.user.username)

    def get_avatar_url(self):
        '''Avatar URL (using custom URL or Gravatar)'''
        if self.avatar_url:
            return self.avatar_url
        else:
            return 'https://secure.gravatar.com/avatar/{0}?d=identicon'.format(md5(self.user.email).hexdigest())

    def get_post_count(self):
        '''Number of messages posted'''
        return Post.objects.all().filter(author__pk=self.user.pk).count()

    def get_topic_count(self):
        '''Number of threads created'''
        return Topic.objects.all().filter(author=self.user).count()
    
    def get_tuto(self):
        '''Tutorial in draft'''
        return Tutorial.objects.all().filter(authors__in=[self.user]).count()
    
    def get_draft_tuto(self):
        '''Tutorial in draft'''
        return Tutorial.objects.all().filter(authors__in=[self.user], sha_public__isnull=True, sha_draft__isnull=False)
    
    def get_public_tuto(self):
        '''Draft tuto'''
        return Tutorial.objects.all().filter(authors__in=[self.user], sha_public__isnull=False)
    
    def get_validate_tuto(self):
        '''Tutorial in validation'''
        return Tutorial.objects.all().filter(authors__in=[self.user], sha_validation__isnull=False)
    
    def get_beta_tuto(self):
        '''Tutorial in beta'''
        return Tutorial.objects.all().filter(authors__in=[self.user], sha_beta__isnull=False)
    
    def get_is_author(self):
        return False
    
    def get_ip_address(self):
        return Post.objects.all().filter(author=self.user)
    
    def get_invisible_posts_count(self):
        return Post.objects.filter(is_visible=False, author=self.user).count()
    
    def get_alerts_posts_count(self):
        return Alert.objects.filter(author=self.user).count()
    
    def can_read_now(self):
        if self.end_ban_read:
            return self.can_read or (self.end_ban_read < datetime.now())
        else:
            return self.can_read
    
    def can_write_now(self):
        if self.end_ban_write:
            return self.can_write or (self.end_ban_write < datetime.now())
        else:
            return self.can_write
        
class Ban(models.Model):
    class Meta:
        verbose_name = 'Sanction'
        verbose_name_plural = 'Sanctions'
        
    user = models.ForeignKey(User, verbose_name='Sanctionné')
    moderator = models.ForeignKey(User, verbose_name='Moderateur',
                                     related_name='bans')
    type = models.CharField('Type',  max_length=15)
    text = models.TextField('Explication de la sanction')
    pubdate = models.DateTimeField('Date de publication', blank=True, null=True)

zds/member/forms.py
# coding: utf-8

from captcha.fields import CaptchaField
from crispy_forms.helper import FormHelper
from crispy_forms_foundation.layout import Layout, Div, Fieldset, Submit, Field, \
    HTML
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

from zds.member.models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=76, widget=forms.PasswordInput)


class RegisterForm(forms.Form):
    email = forms.EmailField(label='Adresse email')
    username = forms.CharField(label='Nom d\'utilisateur', max_length=30)
    password = forms.CharField(
        label='Mot de passe', max_length=76, widget=forms.PasswordInput
    )
    password_confirm = forms.CharField(
        label='Confirmation', max_length=76, widget=forms.PasswordInput
    )
    captcha = CaptchaField()

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.layout = Layout(
            Fieldset(
                u'Identifiants',
                Field('username'),
                Field('password'),
                Field('password_confirm'),
                Field('email'),
            ),
            Fieldset(
                u'Captcha',
                Field('captcha'),
            ),
            Div(
                Submit('submit', 'Valider mon inscription'),
                HTML('<a href="/" class="button secondary">Annuler</a>'),
                css_class='button-group'
            )
        )
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()

        # Check that the password and it's confirmation match
        password = cleaned_data.get('password')
        password_confirm = cleaned_data.get('password_confirm')

        if not password_confirm == password:
            msg = u'Les mots de passe sont différents'
            self._errors['password'] = self.error_class([''])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password' in cleaned_data:
                del cleaned_data['password']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        # Check that the user doesn't exist yet
        username = cleaned_data.get('username')
        if User.objects.filter(username=username).count() > 0:
            msg = u'Ce nom d\'utilisateur est déjà utilisé'
            self._errors['username'] = self.error_class([msg])

        return cleaned_data


# update extra information about user
class ProfileForm(forms.Form):
    biography = forms.CharField(
        label='Biographie',
        required=False,
        widget=forms.Textarea(
            attrs={'placeholder': 'Votre biographie au format Markdown.'}))
    site = forms.CharField(
        label='Site internet',
        required=False,
        max_length=128,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers votre site internet personnel '
                   '(ne pas oublier le http:// ou https:// devant).'}))
    show_email = forms.BooleanField(
        label='Afficher mon adresse mail publiquement',
        required=False)
    
    show_sign = forms.BooleanField(
        label='Afficher les signatures des autres membres',
        required=False)
    
    hover_or_click = forms.BooleanField(
        label='Derouler les menus au survol de la souris ou au clic',
        required=False)
    
    avatar_url = forms.CharField(
        label='Avatar',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Lien vers un avatar externe '
                   '(laisser vide pour utiliser Gravatar).'}))
    sign = forms.CharField(
        label='Signature',
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Elle apparaitra dans les messages de forums. '}
            ))
    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user
        profile = Profile.objects.get(user=self.user)

        # to get initial value form checkbox show email
        initial = kwargs.get('initial', {})
        value_checked_email = ''
        if 'show_email' in initial and initial['show_email']:
            value_checked_email = 'checked'
        
        value_checked_sign = ''
        if 'show_sign' in initial and initial['show_sign']:
            value_checked_sign = 'checked'
            
        value_checked_hover_or_click = ''
        if 'hover_or_click' in initial and initial['hover_or_click']:
            value_checked_hover_or_click = 'checked'

        self.helper.layout = Layout(
            Fieldset(
                u'Public',
                Field('biography'),
                Field('site'),
                Field('avatar_url'),
                Field('sign'),
                # inline checkbox is not supported by crispy form
                HTML('<div id="div_id_show_email" class="ctrlHolder checkbox" style="padding-top:10px">\
                <label for="id_show_email" > <input id="id_show_email" type="checkbox" class="checkboxinput" name="show_email" ' + value_checked_email + '/>\
                Afficher mon adresse mail publiquement</label></div>'),
                HTML('<div id="div_id_show_sign" class="ctrlHolder checkbox" style="padding-top:10px">\
                <label for="id_show_sign" > <input id="id_show_sign" type="checkbox" class="checkboxinput" name="show_sign" ' + value_checked_sign + '/>\
                Afficher les signatures des autres membres</label></div>'),
                HTML('<div id="div_id_hover_or_click" class="ctrlHolder checkbox" style="padding-top:10px">\
                <label for="id_hover_or_click" > <input id="id_hover_or_click" type="checkbox" class="checkboxinput" name="hover_or_click" ' + value_checked_hover_or_click + '/>\
                Derouler les menus au survol de la souris ou au clic</label></div>'),
            ),
            Div(
                Submit('submit', 'Editer mon profil'),
                css_class='button-group'
            )
        )
        super(ProfileForm, self).__init__(*args, **kwargs)


# to update a password

class ChangePasswordForm(forms.Form):
    password_new = forms.CharField(
        label='Nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)
    password_old = forms.CharField(
        label='Mot de passe actuel ', max_length=76, widget=forms.PasswordInput)
    password_confirm = forms.CharField(
        label='Confirmer le nouveau mot de passe ', max_length=76, widget=forms.PasswordInput)

    def __init__(self, user, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.user = user

        self.helper.layout = Layout(
            Fieldset(
                u'Mot de passe',
                Field('password_old'),
                Field('password_new'),
                Field('password_confirm'),
            ),
            Div(
                Submit('submit', 'Changer mon mot de passe'),
                css_class='button-group'
            )
        )
        super(ChangePasswordForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(ChangePasswordForm, self).clean()

        password_old = cleaned_data.get('password_old')
        password_new = cleaned_data.get('password_new')
        password_confirm = cleaned_data.get('password_confirm')

        # Check if the actual password is not empty
        if password_old:
            user_exist = authenticate(
                username=self.user.username, password=password_old
            )
            if not user_exist and password_old != "":
                self._errors['password_old'] = self.error_class(
                    [u'Mot de passe incorrect.'])
                if 'password_old' in cleaned_data:
                    del cleaned_data['password_old']

        # Check that the password and it's confirmation match
        if not password_confirm == password_new:
            msg = u'Les mots de passe sont différents.'
            self._errors['password_new'] = self.error_class([msg])
            self._errors['password_confirm'] = self.error_class([msg])

            if 'password_new' in cleaned_data:
                del cleaned_data['password_new']

            if 'password_confirm' in cleaned_data:
                del cleaned_data['password_confirm']

        return cleaned_data

templates/member/actions.html
{% extends "member/base.html" %}

{% block title %}
    Quoi de neuf ?
{% endblock %}

{% block headline %}
    Quoi de neuf ?
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Quoi de neuf ?</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <h2>Actions</h2>
        <ul>
            <li>
                <a href="{% url "zds.member.views.details" user.username %}">
                    Voir votre profil
                </a>
            </li>
            <li>
                <a href="{% url "zds.member.views.publications" %}">
                    Voir vos publications
                </a>
            </li>
            <li>
                <a href="{% url "zds.member.views.settings_profile" %}">
                    Paramètres de votre profil
                </a>
            </li>
            <li>
                <a href="{% url "zds.member.views.settings_account" %}">
                    Paramètres de votre compte
                </a>
            </li>
        </ul>
    </div>
</div>

{% endblock %}

templates/member/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Membres
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "zds.member.views.index" %}">Membres</a></li>
{% endblock %}

templates/member/edit_profile.html
{% extends "member/base.html" %}
{% load markup %}

{% block title %}
    Éditer mon profil
{% endblock %}

{% block headline %}
    Éditer mon profil
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ profile.user.get_absolute_url }}">{{ profile.user.username }}</a></li>
    <li class="current"><a href="#">Éditer mon profil</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <form action="" method="POST">
            <fieldset>
                <legend>Public</legend>
        
                <div class="control-group">
                    <label for="id_biography" class="control-label">Biographie</label>
                    <div class="controls">
                        <textarea name="biography" class="input-block-level" rows="10" id="id_biography"
                            placeholder="Votre biographie au format Markdown.">{{ profile.biography }}</textarea>
                    </div>
                </div>
        
                <div class="control-group">
                    <label for="id_site" class="control-label">Site internet</label>
                    <div class="controls">
                        <input type="text" name="site" id="id_site" class="input-block-level"
                        placeholder="Lien vers votre site internet personnel." value="{{ profile.site }}"/>
                    </div>
                </div>
        
                <div class="control-group">
                    <label for="id_email" class="control-label">Adresse mail</label>
                    <div class="controls">
                        <input type="text" name="email" id="id_email" class="input-block-level"
                        placeholder="Veuillez entrer une adresse email valide" value="{{ profile.user.email }}"/>
                    </div>
                </div>
        
                <div class="control-group">
                    <div class="controls">
                        <label class="checkbox">
                            <input type="checkbox" name="show_email"
                            {% if profile.show_email %}checked{% endif %}>
                            Afficher mon adresse mail publiquement
                        </label>
                    </div>
                </div>
        
            </fieldset>
            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-pencil icon-white"></i>
                    Éditer
                </button>
        
                <a href="{{ profile.user.get_absolute_url }}" class="button secondary">
                    Annuler
                </a>
            </div>
        
            {% csrf_token %}
        
        </form>
    </div>
</div>



{% endblock %}

templates/member/index.html
{% extends "member/base.html" %}

{% block title %}
    Membres
{% endblock %}

{% block headline %}
    Membres
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Index</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Sur cette page vous pourrez trouver la liste des membres inscrits au site (actuellement {{ members.count }} membres).
        </p>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <p>
            {% for member in members %}
                {% include "member/member_item_common.part.html" %}
            {% endfor %}
        </p>
    </div>
</div>

{% endblock %}

templates/member/login.html
{% extends "member/base.html" %}

{% block title %}
    Connexion
{% endblock %}

{% block headline %}
    Se connecter
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Connexion</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% if not user.is_authenticated %}
            {% if error %}
            <div class="alert-box warning">
                {{ error }}.
            </div>
            {% endif %}

            <p>
                Si vous n'avez pas de compte, vous pouvez <a href="{% url "zds.member.views.register_view" %}" >vous inscrire</a>.
            </p>
        {% else %}
            <p>
                Vous êtes déjà connecté.
            </p>
        {% endif %}
    </div>
</div>

{% if not user.is_authenticated %}
<div class="row">
    <div class="large-7 large-offset-1 columns">
        <form method="post" action="{% url "zds.member.views.login_view" %}">
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_username">Identifiant</label>
                </div>
                <div class="small-8 columns">
                    <input type="text" name="username" id="id_username" maxlength="30" {% if form.username.value %}value="{{ form.username.value }}"{% endif %} />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns">
                    <label class="right inline" for="id_password">Mot magique</label>
                </div>
                <div class="small-8 columns">
                    <input type="password" name="password" id="id_password" maxlength="76" />
                </div>
            </div>
            <div class="row">
                <div class="small-4 columns"></div>
                <div class="small-8 columns">
                    <label>
                        <input type="checkbox" name="remember">
                        Connexion automatique
                    </label>
                </div>
            </div>

            <div class="row">
                <div class="small-8 small-offset-4 columns">
                    <button type="submit" class="button">
                        Se connecter
                    </button>
                    <a href="/" class="button secondary">
                        Annuler
                    </a>
                </div>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

templates/member/member_item_common.part.html
{% load profile %}

{% with profile=member|profile %}
<a href="{{ member.get_absolute_url }}" class="member-item">
    <img src="{{ profile.get_avatar_url }}" width="16" height="16" alt="Avatar" />
    {{ member.username }}
</a>
{% endwith %}

templates/member/publications.html
{% extends "member/base.html" %}

{% block title %}
    Publications
{% endblock %}

{% block headline %}
    Publications
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Publications</a></li>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <h3>Tutoriels</h3>
        </div>
    </div>

    {% if user_tutorials %}
        {% for tuto in user_tutorials %}
            {% if tuto.on_line %}
                <div class="row article-publication-item published">
            {% else %}
                <div class="row article-publication-item">
            {% endif %}
                <div class="large-1 columns">
                    <div class="date-box">
                        {% with date=tuto.update %}
                            {% include "misc/datebox.part.html" %}
                        {% endwith %}
                    </div>
                </div>
                <div class="large-1 columns">
                    <img src="{{ tuto.image.thumb.url }}" />
                </div>
                <div class="large-9 columns">
                    <a href="{{ tuto.get_absolute_url }}">{{ tuto.title }}</a>
                    <p>{{ tuto.description }}</p>
                </div>
                <div class="large-1 columns">
                    <a href="{% url "zds.tutorial.views.edit_tutorial" %}?tutoriel={{ tuto.pk }}">
                        <i class="icon-edit"></i>
                        Éditer
                    </a>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="row">
            <div class="large-12 columns">
                Vous n'avez aucun tutoriel
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/member/register.html
{% extends "member/base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    S'incrire
{% endblock %}

{% block headline %}
    S'inscrire
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">S'inscrire</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        {% if not user.is_authenticated %}
            {% if error %}
                {{ error }}
            {% endif %}
            <p>
                <strong>Vous êtes sur le point de vous inscrire sur Progdupeupl</strong> ; si vous
                possédez déjà un compte, merci de <a href="{% url "zds.member.views.login_view" %}">vous connecter</a>
                à la place.
            </p>
            <p>
                Veuillez fournir les informations nécessaires dans le
                formulaire suivant afin de poursuivre votre inscription.
            </p>
            {% crispy form %}
        {% else %}
            <p>Vous êtes déjà connecté.</p>
        {% endif %}
    </div>
</div>

{% endblock %}

templates/member/register_success.html
{% extends "member/base.html" %}

{% block title %}
    Inscription réussie
{% endblock %}

{% block headline %}
    Inscription réussie
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="#">Inscription</a></li>
{% endblock %}

{% block content %}

<div class="row">
    <div class="large-12 columns">
        <p>
            Vous avez bien été inscrit au site. <a href="{% url "zds.member.views.details" user.username %}">Voir votre profil</a>.
        </p>
    </div>
</div>

{% endblock %}

templates/member/settings_account.html
{% extends "member/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li><a href="{% url "zds.member.views.settings_profile" %}">Paramètres</a></li>
    <li class="current"><a href="#">Compte</a></li>
{% endblock %}

{% block subnav %}
    <dd><a href="{% url "zds.member.views.settings_profile" %}">Profil</a></dd>
    <dd class="active"><a href="{% url "zds.member.views.settings_account" %}">Compte</a></dd>
{% endblock %}

{% block settings_form %}
<div class="row">
    <div class="large-12 columns">
        {% crispy form %}
    </div>
</div>
{% endblock %}

templates/member/settings_base.html
{% extends "member/base.html" %}
{% load markup %}

{% block title %}
   Paramètres
{% endblock %}

{% block headline %}
   Paramètres
{% endblock %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <dl class="sub-nav">
                {% block subnav %}{% endblock %}
            </dl>
        </div>
    </div>
    {% block settings_form %}{% endblock %}
{% endblock %}

templates/member/settings_profile.html
{% extends "member/settings_base.html" %}
{% load crispy_forms_tags %}

{% block breadcrumb %}
    <li><a href="{% url "zds.member.views.settings_profile" %}">Paramètres</a></li>
    <li class="current"><a href="#">Profil</a></li>
{% endblock %}

{% block subnav %}
    <dd class="active"><a href="{% url "zds.member.views.settings_profile" %}">Profil</a></dd>
    <dd><a href="{% url "zds.member.views.settings_account" %}">Compte</a></dd>
{% endblock %}

{% block settings_form %}
    <div class="row">
        <div class="large-12 columns">
            {% crispy form %}
        </div>
    </div>
{% endblock %}