zds/mp/urls.py
# coding: utf-8

from django.conf.urls import patterns, url

import views


urlpatterns = patterns('',

    # Viewing a thread
    url(r'^nouveau$', views.new),
    url(r'^editer$', views.edit),
    url(r'^(?P<topic_pk>\d+)/(?P<topic_slug>.+)$', views.topic),

    # Message-related
    url(r'^message/editer$', views.edit_post),
    url(r'^message/nouveau$', views.answer),
    
    # Home
    url(r'^$', views.index),
)

zds/urls.py
# encoding: utf-8

from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User, Group

import pages.views
import settings


admin.autodiscover()


urlpatterns = patterns('',
    url(r'^tutoriels/', include('zds.tutorial.urls')),
    url(r'^forums/', include('zds.forum.urls')),
    url(r'^mp/', include('zds.mp.urls')),
    url(r'^membres/', include('zds.member.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('zds.pages.urls')),
    url(r'^galerie/', include('zds.gallery.urls')),

    url(r'^captcha/', include('captcha.urls')),

    url(r'^$', pages.views.home),

)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SERVE:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

zds/forum/models.py
# coding: utf-8
import os
import uuid
import string

from math import ceil

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import Group, User
from django.template.defaultfilters import slugify

from zds.utils import get_current_user
from zds.utils.models import Alert

# TODO: Put these constants in settings.py file
POSTS_PER_PAGE = 21
TOPICS_PER_PAGE = 21
SPAM_LIMIT_SECONDS = 60 * 15


def image_path_forum(instance, filename):
    '''Return path to an image'''
    ext = filename.split('.')[-1]
    filename = u'{}.{}'.format(str(uuid.uuid4()), string.lower(ext))
    return os.path.join('forum/normal', str(instance.pk), filename)

class Category(models.Model):
    '''A category, containing forums'''
    class Meta:
        verbose_name = 'Catégorie'
        verbose_name_plural = 'Catégories'

    title = models.CharField('Titre', max_length=80)
    position = models.IntegerField('Position', null=True, blank=True)
    slug = models.SlugField(max_length=80)

    def __unicode__(self):
        '''Textual form of a category'''
        return self.title

    def get_absolute_url(self):
        return '/forums/{0}/'.format(self.slug)

    def get_forums(self):
        return Forum.objects.all()\
            .filter(category=self)\
            .order_by('position_in_category')


class Forum(models.Model):
    '''A forum, containing topics'''
    class Meta:
        verbose_name = 'Forum'
        verbose_name_plural = 'Forums'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)
    
    group = models.ManyToManyField(Group, verbose_name='Groupe autorisés (Aucun = public)', null=True, blank=True)
    image = models.ImageField(upload_to=image_path_forum)
    
    category = models.ForeignKey(Category, verbose_name='Catégorie')
    position_in_category = models.IntegerField('Position dans la catégorie',
                                               null=True, blank=True)

    slug = models.SlugField(max_length=80)
    
    def __unicode__(self):
        '''Textual form of a forum'''
        return self.title

    def get_absolute_url(self):
        return '/forums/{0}/{1}/'.format(
            self.category.slug,
            self.slug,
        )

    def get_topic_count(self):
        '''Gets the number of threads in the forum'''
        return Topic.objects.all().filter(forum__pk=self.pk).count()

    def get_post_count(self):
        return Post.objects.all().filter(topic__forum=self).count()

    def get_last_message(self):
        '''Gets the last message on the forum, if there are any'''
        try:
            return Post.objects.all().filter(topic__forum__pk=self.pk).order_by('-pubdate')[0]
        except IndexError:
            return None

    def is_read(self):
        for t in Topic.objects.all().filter(forum=self):
            if never_read(t):
                return False
        return True

class Topic(models.Model):
    '''A thread, containing posts'''
    class Meta:
        verbose_name = 'Sujet'
        verbose_name_plural = 'Sujets'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    forum = models.ForeignKey(Forum, verbose_name='Forum')
    author = models.ForeignKey(User, verbose_name='Auteur',
                                     related_name='topics')
    last_message = models.ForeignKey('Post', null=True,
                                     related_name='last_message',
                                     verbose_name='Dernier message')
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)

    is_solved = models.BooleanField('Est résolu')
    is_locked = models.BooleanField('Est verrouillé')
    is_sticky = models.BooleanField('Est en post-it')

    def __unicode__(self):
        '''
        Textual form of a thread
        '''
        return self.title

    def get_absolute_url(self):
        return '/forums/sujet/{0}/{1}'.format(self.pk, slugify(self.title))

    def get_post_count(self):
        '''
        Return the number of posts in the topic
        '''
        return Post.objects.all().filter(topic__pk=self.pk).count()

    def get_last_answer(self):
        '''
        Gets the last answer in the thread, if any
        '''
        last_post = Post.objects.all()\
            .filter(topic__pk=self.pk)\
            .order_by('-pubdate')[0]

        if last_post == self.first_post():
            return None
        else:
            return last_post

    def first_post(self):
        '''
        Return the first post of a topic, written by topic's author
        '''
        return Post.objects\
            .filter(topic=self)\
            .order_by('pubdate')[0]

    def last_read_post(self):
        '''
        Return the last post the user has read
        '''
        try:
            return TopicRead.objects\
                .select_related()\
                .filter(topic=self, user=get_current_user())\
                .latest('post__pubdate').post
        except Post.DoesNotExist:
            return self.first_post()

    def is_followed(self, user=None):
        '''
        Check if the topic is currently followed by the user. This method uses
        the TopicFollowed objects.
        '''
        if user is None:
            user = get_current_user()

        try:
            TopicFollowed.objects.get(topic=self, user=user)
        except TopicFollowed.DoesNotExist:
            return False
        return True

    def antispam(self, user=None):
        '''
        Check if the user is allowed to post in a topic according to the
        SPAM_LIMIT_SECONDS value. If user shouldn't be able to post, then
        antispam is activated and this method returns True. Otherwise time
        elapsed between user's last post and now is enough, and the method will
        return False.
        '''
        if user is None:
            user = get_current_user()

        last_user_posts = Post.objects\
            .filter(topic=self)\
            .filter(author=user)\
            .order_by('-pubdate')

        if last_user_posts and last_user_posts[0] == self.get_last_answer():
            last_user_post = last_user_posts[0]
            t = timezone.now() - last_user_post.pubdate
            if t.total_seconds() < SPAM_LIMIT_SECONDS:
                return True

        return False

    def never_read(self):
        return never_read(self)


class Post(models.Model):
    '''
    A forum post written by an user.
    '''
    
    topic = models.ForeignKey(Topic, verbose_name='Sujet')
    author = models.ForeignKey(User, verbose_name='Auteur',
                                     related_name='posts')
    ip_address = models.CharField('Adresse IP de l\'auteur ', max_length=15)
    text = models.TextField('Texte')
    text_html = models.TextField('Texte en Html')
    
    like = models.IntegerField('Likes', default=0)
    dislike = models.IntegerField('Dislikes', default=0)

    pubdate = models.DateTimeField('Date de publication', auto_now_add=True)
    update = models.DateTimeField('Date d\'édition', null=True, blank=True)

    position_in_topic = models.IntegerField('Position dans le sujet')

    is_useful = models.BooleanField('Est utile', default=False)
    is_visible = models.BooleanField('Est visible', default=True)
    text_hidden = models.CharField('Texte de masquage ', max_length=80, default='')
    
    alerts = models.ManyToManyField(Alert, verbose_name='Alertes', null=True, blank=True)

    def __unicode__(self):
        '''Textual form of a post'''
        return u'<Post pour "{0}", #{1}>'.format(self.topic, self.pk)

    def get_absolute_url(self):
        page = int(ceil(float(self.position_in_topic) / POSTS_PER_PAGE))

        return '{0}?page={1}#p{2}'.format(self.topic.get_absolute_url(), page, self.pk)

    def get_like_count(self):
        return PostLike.objects.filter(posts__pk=self.pk).count()
    
    def get_dislike_count(self):
        return PostDislike.objects.filter(posts__pk=self.pk).count()

class TopicRead(models.Model):
    '''
    Small model which keeps track of the user viewing topics. It remembers the
    topic he looked and what was the last Post at this time.
    '''
    class Meta:
        verbose_name = 'Sujet lu'
        verbose_name_plural = 'Sujets lus'

    topic = models.ForeignKey(Topic)
    post = models.ForeignKey(Post)
    user = models.ForeignKey(User, related_name='topics_read')

    def __unicode__(self):
        return u'<Sujet "{0}" lu par {1}, #{2}>'.format(self.topic,
                                                        self.user,
                                                        self.post.pk)


class TopicFollowed(models.Model):
    '''
    Small model which keeps track of the topics followed by an user. If an
    instance of this model is stored with an user and topic instance, that
    means that this user is following this topic.
    '''
    class Meta:
        verbose_name = 'Sujet suivi'
        verbose_name_plural = 'Sujets suivis'

    topic = models.ForeignKey(Topic)
    user = models.ForeignKey(User, related_name='topics_followed')

    def __unicode__(self):
        return u'<Sujet "{0}" suivi par {1}>'.format(self.topic.title,
                                                     self.user.username)

class PostLike(models.Model):
    '''
    Set of like posts
    '''
    class Meta:
        verbose_name = 'Ce message est utile'
        verbose_name_plural = 'Ces messages sont utiles'

    posts = models.ForeignKey(Post)
    user = models.ForeignKey(User, related_name='post_liked')

class PostDislike(models.Model):
    '''
    Set of dislike posts
    '''
    class Meta:
        verbose_name = 'Ce message est inutile'
        verbose_name_plural = 'Ces messages sont inutiles'

    posts = models.ForeignKey(Post)
    user = models.ForeignKey(User, related_name='post_disliked')


def never_read(topic, user=None):
    '''

zds/mp/models.py
# coding: utf-8

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils import timezone
from math import ceil

from zds.utils import get_current_user


# TODO: Put these constants in settings.py file
POSTS_PER_PAGE = 21
TOPICS_PER_PAGE = 21
SPAM_LIMIT_SECONDS = 60 * 15
SPAM_LIMIT_PARTICIPANT = 2


class PrivateTopic(models.Model):
    '''Topic private, containing private posts'''
    class Meta:
        verbose_name = 'Message privé'
        verbose_name_plural = 'Messages privés'

    title = models.CharField('Titre', max_length=80)
    subtitle = models.CharField('Sous-titre', max_length=200)

    author = models.ForeignKey(User, verbose_name='Auteur',
                                     related_name='author')
    participants = models.ManyToManyField(User, verbose_name='Participants',
                                     related_name='participants')
    last_message = models.ForeignKey('PrivatePost', null=True,
                                     related_name='last_message',
                                     verbose_name='Dernier message')
    pubdate = models.DateTimeField('Date de création', auto_now_add=True)

    def __unicode__(self):
        '''
        Textual form of a thread
        '''
        return self.title

    def get_absolute_url(self):
        return '/mp/{0}/{1}'.format(self.pk, slugify(self.title))

    def get_post_count(self):
        '''
        Return the number of private posts in the private topic
        '''
        return PrivatePost.objects.all().filter(privatetopic__pk=self.pk).count()

    def get_last_answer(self):
        '''
        Gets the last answer in the thread, if any
        '''
        last_post = PrivatePost.objects.all()\
            .filter(privatetopic__pk=self.pk)\
            .order_by('-pubdate')[0]

        if last_post == self.first_post():
            return None
        else:
            return last_post

    def first_post(self):
        '''
        Return the first post of a topic, written by topic's author
        '''
        return PrivatePost.objects\
            .filter(privatetopic=self)\
            .order_by('pubdate')[0]

    def last_read_post(self):
        '''
        Return the last private post the user has read
        '''
        try:
            post = PrivateTopicRead.objects\
            .select_related()\
            .filter(privatetopic=self, user=get_current_user())
            if len(post)==0:
                return self.first_post()
            else: 
                return post.latest('privatepost__pubdate').privatepost 
        
        except PrivatePost.DoesNotExist:
            return self.first_post()

    def antispam(self, user=None):
        '''
        Check if the user is allowed to post in a topic according to the
        SPAM_LIMIT_SECONDS value. If user shouldn't be able to post, then
        antispam is activated and this method returns True. Otherwise time
        elapsed between user's last post and now is enough, and the method will
        return False.
        '''
        if user is None:
            user = get_current_user()

        last_user_privateposts = PrivatePost.objects\
            .filter(privatetopic=self)\
            .filter(author=user)\
            .order_by('-pubdate')

        if last_user_privateposts and last_user_privateposts[0] == self.get_last_answer():
            last_user_privatepost = last_user_privateposts[0]
            t = timezone.now() - last_user_privatepost.pubdate
            if t.total_seconds() < SPAM_LIMIT_SECONDS:
                return True

        return False

    def never_read(self):
        return never_privateread(self)
    


class PrivatePost(models.Model):
    '''
    A private post written by an user.
    '''
    privatetopic = models.ForeignKey(PrivateTopic, verbose_name='Message privé')
    author = models.ForeignKey(User, verbose_name='Auteur',
                                     related_name='privateposts')
    text = models.TextField('Texte')

    pubdate = models.DateTimeField('Date de publication', auto_now_add=True)
    update = models.DateTimeField('Date d\'édition', null=True, blank=True)

    position_in_topic = models.IntegerField('Position dans le sujet')

    def __unicode__(self):
        '''Textual form of a post'''
        return u'<Post pour "{0}", #{1}>'.format(self.privatetopic, self.pk)

    def get_absolute_url(self):
        page = int(ceil(float(self.position_in_topic) / POSTS_PER_PAGE))

        return '{0}?page={1}#p{2}'.format(self.privatetopic.get_absolute_url(), page, self.pk)


class PrivateTopicRead(models.Model):
    '''
    Small model which keeps track of the user viewing private topics. It remembers the
    topic he looked and what was the last private Post at this time.
    '''
    class Meta:
        verbose_name = 'Message privé lu'
        verbose_name_plural = 'Messages privés lus'

    privatetopic = models.ForeignKey(PrivateTopic)
    privatepost = models.ForeignKey(PrivatePost)
    user = models.ForeignKey(User, related_name='privatetopics_read')

    def __unicode__(self):
        return u'<Sujet "{0}" lu par {1}, #{2}>'.format(self.privatetopic,
                                                        self.user,
                                                        self.privatepost.pk)
    
def never_privateread(privatetopic, user=None):
    '''
    Check if a private topic has been read by an user since it last post was added.
    '''
    if user is None:
        user = get_current_user()

    return PrivateTopicRead.objects\
        .filter(privatepost=privatetopic.last_message, privatetopic=privatetopic, user=user)\
        .count() == 0


def mark_read(privatetopic):
    '''
    Mark a private topic as read for the user
    '''
    PrivateTopicRead.objects.filter(privatetopic=privatetopic, user=get_current_user()).delete()
    t = PrivateTopicRead(
        privatepost=privatetopic.last_message, privatetopic=privatetopic, user=get_current_user())
    t.save()


def get_last_privatetopics():
    '''
    Returns the 5 very last topics
    '''
    return PrivateTopic.objects.all().order_by('-pubdate')[:5]

templates/mp/answer.html
{% extends "mp/base.html" %}
{% block title %}
    Répondre au MP
{% endblock %}

{% block headline %}
    Répondre au MP
{% endblock %}

{% block headline-sub %}
    {{ topic.title }}
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a></li>
    <li class="current"><a href="javascript:;">Répondre au MP</a></li>
{% endblock %}

{% block content %}

{% if newpost %}
<div class="row">
    <div class="large-12 columns">
        <div class="alert-box alert">
            <strong>Au moins un nouveau message a été posté</strong> dans la discussion
            pendant que vous rédigiez le votre.
        </div>
    </div>
</div>
{% endif %}

{% include "misc/editor.part.html" %}

<div class="row">
    <div class="large-12 columns">
        <form action="#previsualisation" method="POST">
            <textarea class="input-block-level" name="text" rows="20" id="id_text"
                placeholder="Contenu de votre message au format Markdown.">{{ text }}</textarea>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-ok icon-white"></i>
                    Répondre
                </button>

                <button type="submit" name="preview" class="button secondary">
                    <i class="icon-eye-open"></i>
                    Prévisualisation
                </button>

                <a href="{{ topic.get_absolute_url }}" class="button secondary">
                    <i class="icon-remove"></i>
                    Annuler
                </a>
            </div>

            <input type="hidden" name="last_post" value="{{ last_post_pk }}" />
            {% csrf_token %}
        </form>
    </div>
</div>

{% if text %}
    {% include "mp/previsualization.part.html" %}
{% endif %}

{% endblock %}

templates/mp/base.html
{% extends "base.html" %}

{% block title_base %}
    &#183; Messages Privés
{% endblock %}

{% block breadcrumb_base %}
    <li><a href="{% url "zds.mp.views.index" %}">Messages Privés</a></li>
{% endblock %}

{% block menu_mp %}
    active
{% endblock %}

templates/mp/edit_post.html
{% extends "mp/base.html" %}

{% block title %}
    Éditer un message
{% endblock %}

{% block headline %}
    Éditer un message
{% endblock %}

{% block breadcrumb %}
    <li><a href="{{ post.topic.get_absolute_url }}">{{ post.privatetopic.title }}</a></li>
    <li class="current"><a href="javascript:;">Éditer un message</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <div>
            <p>
            <strong>Participants :</strong> 
            {% with member=post.privatetopic.author %}
                {% include "member/member_item_common.part.html" %}
            {% endwith %}
            {% for member in post.privatetopic.participants.all %}
                | {% include "member/member_item_common.part.html" %}
            {% endfor %}
            </p>
        </div>
        <form action="#previsualisation" method="POST">
            {% if topic %}
            <fieldset>
                <legend>Sujet</legend>
                <div class="control-group">
                    <label class="control-label" for="id_title">Titre</label>
                    <div class="controls">
                        <input type="text" name="title" id="id_title"
                            class="input-xxlarge" value="{{ topic.title }}" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="id_subtitle">Sous titre</label>
                    <div class="controls">
                        <input type="text" name="subtitle" id="id_subtitle"
                            class="input-xxlarge" value="{{ topic.subtitle }}" />
                    </div>
                </div>
            </fieldset>
            {% endif %}
            {% include "misc/editor.part.html" %}
            <fieldset>
                <legend>Message</legend>
                <div class="control-group">
                    <label class="control-label" for="id_text">Texte</label>
                    <div class="controls">
                        <textarea id="id_text" name="text"
                            class="input-block-level" rows="20">{{ text }}</textarea>
                    </div>
                </div>
            </fieldset>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    Éditer
                </button>

                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>

                <a href="{{ post.get_absolute_url }}" class="button secondary">Annuler</a>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>

{% include "forum/previsualization.part.html" %}

{% endblock %}

templates/mp/new.html
{% extends "mp/base.html" %}
{% load emarkdown %}
{% load markup %}

{% block title %}
    Nouvel MP
{% endblock %}

{% block headline %}
    Nouvel MP
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">Nouvel MP</a></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="large-12 columns">
        <form action="" method="POST">
            <input type="text" placeholder="Participants (séparés par une virgule)" name="participants" class="input-xxlarge" value="{{ participants }}" /><br />
            <input type="text" placeholder="Titre" name="title" class="input-xxlarge" value="{{ title }}" /><br />
            <input type="text" placeholder="Sous-titre" name="subtitle" class="input-xxlarge" value="{{ subtitle }}" /><br />
            <textarea class="input-block-level" rows="20" name="text" id="id_text"
                placeholder="Contenu de votre message au format Markdown.">{{ text }}</textarea>

            <div style="text-align: center;">
                <button type="submit" class="button">
                    <i class="icon-plus icon-white"></i>
                    Nouvel MP
                </button>

                <button type="submit" name="preview" class="button secondary">
                    Prévisualisation
                </button>

                <a href="{{ forum.get_absolute_url }}" class="button secondary">
                    Retour
                </a>
            </div>

            {% csrf_token %}
        </form>
    </div>
</div>

{% if text %}
<div class="row">
    <div class="large-12 columns">
        <div class="panel">
            <h5>Prévisualisation de votre message</h5>
            {{ text|emarkdown }}
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

templates/mp/previsualization.part.html
{% load emarkdown %}
<div class="row" id="previsualisation">
    <div class="large-12 columns">
        <div class="panel">
            <h5>Prévisualisation de votre message</h5>
            {{ text|emarkdown }}
        </div>
    </div>
</div>

templates/mp/topic.html
{% extends "mp/base.html" %}
{% load emarkdown %}
{% load markup %}
{% load humane_date %}
{% load profile %}

{% block title %}
    {{ topic.title }}
{% endblock %}

{% block headline %}
    <a href="{{ topic.get_absolute_url }}">
        {{ topic.title }}
    </a>
{% endblock %}

{% block headline-sub %}
    {{ topic.subtitle }}
{% endblock %}

{% block breadcrumb %}
    <li class="current"><a href="javascript:;">{{ topic.title }}</a></li>
{% endblock %}

{% block headline-actions %}
    {% if user.is_authenticated %}
        <form action="{% url "zds.mp.views.edit" %}" method="POST"
        class="topic-actions" >
            <input type="hidden" name="privatetopic" value="{{ topic.pk }}" />
            <input type="hidden" name="page" value="{{ nb }}">
            <div class="button-group">
                <a href="{% url "zds.mp.views.new" %}" class="button small">
                    <i class="fi-mail"></i>
                    Nouvel MP
                </a>
                {% if topic.author == user %}
                <a href="#" data-dropdown="add-member"  data-options="is_hover:true" class="button small secondary">
                    <i class="fi-torso"></i>
                    Ajouter un membre
                </a>
                <ul id="add-member" class="f-dropdown" data-dropdown-content>
                    <li>
                        <input type="text" placeholder="Pseudo" name="username" />
                    </li>
                </ul>
                {% endif %}
            </div>

            {% csrf_token %}
        </form>
    {% endif %}
{% endblock %}

{% block content %}
<div class="row">
    <p>
            <strong>Participants :</strong> 
        {% with member=topic.author %}
            {% include "member/member_item_common.part.html" %}
        {% endwith %}
        {% for member in topic.participants.all %}
            | {% include "member/member_item_common.part.html" %}
        {% endfor %}
        </p>

</div>
{% include "mp/topic_pagination.part.html" %}

{% for post in posts %}
<div class="post {% if forloop.first and nb > 1 %}before{% endif %} {% if post.is_useful %}useful{% endif %}">
        <div class="row post-head" id="p{{ post.id }}">
            <div class="large-2 columns post-nickname">
                <p>
                    <a href="{{ post.author.get_absolute_url }}">
                        {{ post.author.username }}
                    </a>
                </p>
            </div>
            <div class="large-10 columns">
                <div class="right">
                    {% if user.is_authenticated %}
                        <div class="button-group">
                            {% if post == topic.last_message %}
                            {% if post.author == user or perms.mp.change_post %}
                                <a href="/mp/message/editer?message={{ post.pk }}" class="button secondary small">
                                    <i class="icon-pencil"></i>
                                    Éditer
                                </a>
                            {% endif %}
                            {% endif %}
                            {% if not topic.is_locked and not topic.antispam %}
                                <a href="/mp/message/nouveau?sujet={{ topic.pk }}&amp;cite={{ post.pk }}"
                                    class="button secondary small">
                                    <i class="icon-quote-left"></i>
                                    Citer
                                </a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                <p>
                    <a href="#p{{ post.pk }}">#</a>
                    {{ post.pubdate|humane_date }}
                    {% if not post.update = None %}
                        (dernière édition {{ post.update|humane_date }})
                    {% endif %}
                    {% if forloop.first and nb > 1 %}
                        &ndash; page précédente
                    {% endif %}
                </p>
            </div>
        </div>
        <div class="row post-content">
            <div class="large-2 columns hide-for-small post-avatar">
                {% with profile=post.author|profile %}
                    <img src="{{ profile.get_avatar_url }}" width="80" height="80" alt="Avatar" />
                {% endwith %}
            </div>
            <div class="large-10 columns">
                {{ post.text|emarkdown }}
            </div>
        </div>
    </div>
{% endfor %}

{% include "mp/topic_pagination.part.html" %}

{% if user.is_authenticated %}
<hr />
<form action="{% url "zds.mp.views.answer" %}?sujet={{ topic.pk }}"
method="POST" id="submit_form">
    <div class="row">
        <div class="large-12 columns">
            <h3>Ajouter une réponse</h3>
            {% include "misc/editor.part.html" %}
            <textarea id='id_text' name="text" rows="10" {% if topic.is_locked or topic.antispam %}disabled{% endif %}
                placeholder="Votre message au format Markdown.">{% spaceless %}
                    {% if topic.antispam  %}
                        Vous ne pouvez pas encore poster dans ce sujet (protection antispam de 15 min).
                    {% endif %}
                {% endspaceless %}</textarea>
        </div>
    </div>
    <div class="row">
        <div class="large-8 large-centered columns" style="text-align: center;">
            <button class="button btn-primary" type="submit" {% if topic.is_locked or topic.antispam %}disabled{% endif %}>
                <i class="icon-reply"></i>
                Répondre
            </button>
            <button type="submit" name="preview" class="button secondary" {% if topic.is_locked or topic.antispam %}disabled{% endif %}>
                Prévisualiser
            </button>
        </div>
    </div>
    <input type="hidden" name="last_post" value="{{ last_post_pk }}" />
    {% csrf_token %}
</form>
{% endif %}

{% endblock %}

{% block additionnal-js %}
    <script>
        /* anwser check */
        $('#submit_form').submit(function(e){
            if (!$(this).find('textarea').val()) {
                alert('Votre message ne peut pas être vide.');
                e.preventDefault();
            }
        })
        /* on button press, store it */
        $('#edit_form button[type="submit"]').on('click', function() {
            $('#edit_form').data('button', this.name);    
        });
        /* on submit */
        $('#edit_form').submit(function(e){
            e.preventDefault();
            /* build data */
            var button = $(this).data('button');
            var data = { topic: {{ topic.pk }}};
            data[button] = 'true';
        });
    </script>
{% endblock %}